apiVersion: v1 
kind: Namespace
metadata:
  name: facum

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: facum
  labels:
    app: challengeFinal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deploy
    spec:
      containers:
      - name: frontend-cont
        image: facumiglio/frontend:1.0.0
        env:
          - name: PRODUCTS_SERVICE
            value: products-service
          - name: SHOPPING_CART_SERVICE
            value: shopping-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: facum
  labels:
    app: challengeFinal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: challengeFinal
  template:
    metadata:
      labels:
        app: challengeFinal
    spec:
      containers:
      - name: products-cont
        image: facum/products:1.0.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  namespace: facum
  labels:
    app: challengeFinal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-deploy
  template:
    metadata:
      labels:
        app: shopping-deploy
    spec:
      containers:
      - name: shopping-cont
        image: facum/shopping:1.0.0

