apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: facum
spec:
  selector:
    app: frontend-deploy
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: products-svc
  namespace: facum
spec:
  selector:
    app: challengeFinal
  ports:
  - port: 3001
    targetPort: 3001

apiVersion: v1
kind: Service
metadata:
  name: shopping-svc
  namespace: facum
spec:
  selector:
    app: shopping-deploy
  ports:
  - port: 3002
    targetPort: 3002
